### ISSUE TITLE
Landscape: Single-tap (switch fullscreen mode) does not work propertly

### ISSUE THREAD

**Issue by breviar-sk** [gyim/breviar-ios#61] opened 2020-01-14 09:38 UTC
When the device (iPhone 7 with iOS 13) is in fullscreen on landscape, single-tap gesture shows navigation at the top & bottom but next single-tap gesture does not hide them (i. e. does not work propertly).

Moreover: when on portrait, top bar contains also time. When on landscape, top bar - eventhough it is wider - does not show time. Why? Technical note: In portrait, there are actually two lines (first - system line, second - app line); could there be combined in landscape?

**Comment by gyim** [comment] 2020-01-18 16:00
@breviar-sk Thank you for the bugreport, fixed in the commit 377e3a5. It seems that since iOS 13 the status bar (time + carrier + battery) is hidden in landscape mode if the screen is narrow (on iPhones, but not on iPads). So to answer your second question, this is now the expected behavior. And we can only combine the navigation bar and the status bar if we try to emulate what Apple does in portrait mode and put it somewhere to the navigation bar.

This change of behavior also caused the bug: the app used the presence of the status bar to determine whether it should switch to fullscreen mode or not. Since the status bar was always hidden in landscape mode on iPhones, the fullscreen mode did not work.

**Closed by gyim** 2020-01-18 16:00 UTC
